### ISSUE TITLE
Tracking issue for new methods to add

### ISSUE THREAD

**Issue by RundownRhino** [RundownRhino/smart_iterator#2]
- [ ] A wrapper over `itertools.islice`
- [ ] `step_by` (a special case of `islice`)
- [ ] Perhaps also `nth` (which is `islice` + `next`, but convenient to have).
- [ ] `scan`? Would have to think about what a python alternative would be.
